[build-system]
requires = ["setuptools>=68.2.0", "wheel", "Cython>=3.0", "numpy>=1.21"]
build-backend = "setuptools.build_meta"

[project]
name = "Modal-Decomposition"
version = "0.2.0"
requires-python = ">=3.10"

authors = [
  {name = "Mao_HaoChuan", email = "2215269365@qq.com"},
]
description = "a package for modal decomposition"
readme = "README.md"
license = {text = "Apache-2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",

    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "numpy",
    "EMD-signal",
    "ewtpy",
    "scipy",
    "vmdpy",
    "psutil"
]

optional-dependencies = {"dev"=["pytest>=7.0", "black"], "plot"=["matplotlib"]}

[project.urls]
homepage = "https://github.com/a-raining-day/Modal-Decomposition"
repository = "https://github.com/a-raining-day/Modal-Decomposition.git"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.cibuildwheel]
build = "cp310-* cp311-* cp312-* cp313-*"
skip = "*-musllinux*"